// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-jobs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-jobs.ts
var search_jobs_default = defineTool({
  name: "search_jobs",
  title: "Search government jobs",
  description: "Search active Pakistani government job listings by keyword, province, or education level.",
  inputSchema: {
    query: z.string().optional().describe("Keyword matched against job title and department."),
    province: z.string().optional().describe("Province name, e.g. Punjab or Sindh."),
    education_level: z.string().optional().describe("Education level value, e.g. matric, intermediate, bachelors, masters, phd."),
    limit: z.number().int().optional().describe("Maximum jobs to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, province, education_level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    let q = supabase.from("jobs").select(
      "id,title,department,description,required_education_levels,provinces,min_age,max_age,total_seats,last_date,total_fee,advertisement_link"
    ).eq("is_active", true).order("created_at", { ascending: false }).limit(max);
    if (query?.trim()) {
      const safe = query.replace(/[\\%_*]/g, "\\$&").replace(/[,()]/g, " ").trim();
      if (safe) q = q.or(`title.ilike.%${safe}%,department.ilike.%${safe}%`);
    }
    if (province?.trim()) q = q.contains("provinces", [province.trim()]);
    if (education_level?.trim()) q = q.contains("required_education_levels", [education_level.trim()]);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const jobs = (data ?? []).map((j) => ({
      ...j,
      url: `https://pkjobs.lovable.app/jobs/${j.id}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(jobs, null, 2) }],
      structuredContent: { jobs, count: jobs.length }
    };
  }
});

// src/lib/mcp/tools/get-job.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_job_default = defineTool2({
  name: "get_job",
  title: "Get job details",
  description: "Fetch the full details of a single job listing by its id, including fee breakdown.",
  inputSchema: { job_id: z2.string().describe("The job id (UUID).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("jobs").select("*").eq("id", job_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No job found with that id." }], isError: true };
    const job = { ...data, url: `https://pkjobs.lovable.app/jobs/${data.id}` };
    return {
      content: [{ type: "text", text: JSON.stringify(job, null, 2) }],
      structuredContent: { job }
    };
  }
});

// src/lib/mcp/tools/list-my-applications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_applications_default = defineTool3({
  name: "list_my_applications",
  title: "List my applications",
  description: "List the signed-in user's job applications with their current status and linked job details.",
  inputSchema: {
    status: z3.string().optional().describe("Optional status filter, e.g. pending, in_progress, completed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("applications").select("id,job_id,status,payment_amount,payment_date,notes,created_at,jobs(title,department,last_date)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (status?.trim()) q = q.eq("status", status.trim());
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Fetch the signed-in user's profile, including education entries used for job eligibility.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this user." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/apply-to-job.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var apply_to_job_default = defineTool5({
  name: "apply_to_job",
  title: "Apply to a job",
  description: "Submit an application for the signed-in user to a job listing. Fails if an application already exists.",
  inputSchema: { job_id: z4.string().describe("The job id (UUID) to apply for.") },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ job_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: job, error: jobError } = await supabase.from("jobs").select("id,title,total_fee,is_active").eq("id", job_id).maybeSingle();
    if (jobError) return { content: [{ type: "text", text: jobError.message }], isError: true };
    if (!job || !job.is_active) {
      return { content: [{ type: "text", text: "This job is not available." }], isError: true };
    }
    const { data: existing } = await supabase.from("applications").select("id").eq("user_id", userId).eq("job_id", job_id).maybeSingle();
    if (existing) {
      return {
        content: [{ type: "text", text: "You have already applied for this job." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("applications").insert({ user_id: userId, job_id, payment_amount: job.total_fee, status: "pending" }).select("id,job_id,status,payment_amount,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        { type: "text", text: `Application submitted for "${job.title}". ${JSON.stringify(data)}` }
      ],
      structuredContent: { application: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qrxgpjvhepznplmpctbw";
var mcp_default = defineMcp({
  name: "career-companion",
  title: "Career Companion",
  version: "0.1.0",
  instructions: "Tools for PakJobs, a Pakistani government job platform. Use `search_jobs` and `get_job` to browse listings, `get_my_profile` for the signed-in user's details, `check_my_eligibility` for a per-criterion eligibility verdict on a job, `list_my_applications` and `track_my_applications` to review application status and milestones, `apply_to_job` to submit an application, and `create_job` (admins only) to publish a new listing.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_jobs_default, get_job_default, get_my_profile_default, list_my_applications_default, apply_to_job_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
